name: Build & Push Docker images

on:
  push:
    branches:
      - main
      - 'feat/**'     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image(s)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.multi
          target: api-build     
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/gradient-ds/librechat-api:${{ github.sha }}
            ghcr.io/gradient-ds/librechat-api:${{ github.ref_name }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/gradient-ds/librechat-api:latest' || '' }}